# The URL the site will be built for
base_url = "https://retr0ville.github.io"

theme = "neovim-theme"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
external_links_class = "external"
render_emoji = true

[markdown.highlighting]
theme = "catppuccin-mocha"
code = true
#error_on_missing_language = true

[extra]
# Put all your custom variables here


######################
# Mandatory settings #
######################

# set the name of the blog
blog_name = "Rtrvl's Log"

#####################
# Optional settings #
#####################

# set the background image u want
# background-image = "assets/background.jpg"
# background-image = "https://i.ibb.co/kBmDY1S/Wallpapers-Gram4k-hellpoint-2020-h0.jpg"

# this parameter allow you to configure specific init functions/shortcuts and commands
# the value has to be the path of you're config.js file
# config_js = "config.js"

# allow you to include custom css into your blog
# custom_css = "/css/custom.css"
